{
  "formatVersion": "1.1",
  "component": {
    "group": "me.manga.kira.source",
    "module": "source-contract",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "source-contract-metadata-0.1.0.jar",
          "url": "source-contract-0.1.0.jar",
          "size": 10929,
          "sha512": "d086a22d93c0a8ea029dd5aa7073cb49a272e3d6f3e6f2b01e77e72486b3b6cf6fe4a41ccc45f21199934dc8018179db176d835b5a5af9fd23373ecffb027938",
          "sha256": "94d4c352233c4677b8e8ff9c691f63e89bcb272c690df7ab5af3904329154f2d",
          "sha1": "73f8c366f4fcbbe48635e0db50e2e4e34e19e6d4",
          "md5": "ac18df7cc7c9963cd6df5e3840fdb5b1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "source-contract-kotlin-0.1.0-sources.jar",
          "url": "source-contract-0.1.0-sources.jar",
          "size": 12555,
          "sha512": "63a7a8b797a9963f6a004079810e887030f88cd859cc3b0592f5c900a1598b3ccdaed851baf786735decd5adb364d0d9e994d26697e7f754e9e9dc102b831632",
          "sha256": "ff2332dbd8addbbc69b2c8c3e9c7e6d5e7d1f94e676d532be593a92cd9fafa5b",
          "sha1": "c3a5a836b66335c76c74836d97d18789daabcf7f",
          "md5": "c9902bbd27b278b48cd07e7bd741f7dd"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../source-contract-android/0.1.0/source-contract-android-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../source-contract-android/0.1.0/source-contract-android-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../source-contract-android/0.1.0/source-contract-android-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-contract-iosarm64/0.1.0/source-contract-iosarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-contract-iosarm64/0.1.0/source-contract-iosarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-contract-iosarm64/0.1.0/source-contract-iosarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-contract-iossimulatorarm64/0.1.0/source-contract-iossimulatorarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-contract-iossimulatorarm64/0.1.0/source-contract-iossimulatorarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-contract-iossimulatorarm64/0.1.0/source-contract-iossimulatorarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../source-contract-jvm/0.1.0/source-contract-jvm-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../source-contract-jvm/0.1.0/source-contract-jvm-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../source-contract-jvm/0.1.0/source-contract-jvm-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-contract-jvm",
        "version": "0.1.0"
      }
    }
  ]
}
