{
  "formatVersion": "1.1",
  "component": {
    "group": "me.manga.kira.source",
    "module": "source-engine",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "me.manga.kira.source",
          "module": "source-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "source-engine-metadata-0.1.0.jar",
          "url": "source-engine-0.1.0.jar",
          "size": 12305,
          "sha512": "de123e6315c7deea8d5debeb7d876c530da329d7d48e55e36169e447a427a22c46c4b47b8cfe18f23710c0ccf06f90b94988ce9f4dd9b1b46d4c30532179defb",
          "sha256": "3a2fd051891c305bdc01537fec623070b83426c39cfd8ffac872eb8026ca4a03",
          "sha1": "8140ea7203ca800b7eba7e84d0e364269ca214aa",
          "md5": "c703da3b82b08c5509c98d8323a6460f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "source-engine-kotlin-0.1.0-sources.jar",
          "url": "source-engine-0.1.0-sources.jar",
          "size": 33681,
          "sha512": "fe5572679cf8205d50949956ebb39158693713be9aec46c4fb58d411b0b480f2496482aa6f282f8b8dc520b243a8cb8586ea1390dd1ac6a70ccd653f26265ff8",
          "sha256": "84b4b25e9dd952a99c32618bd217571177feabe80801a6a5466e2afbe71e448d",
          "sha1": "0b5f47f1b89f3eb7fb1cfd16fd99ae90d1d89554",
          "md5": "5288d57e3c7e505ab5db335803a46fd1"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../source-engine-android/0.1.0/source-engine-android-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../source-engine-android/0.1.0/source-engine-android-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../source-engine-android/0.1.0/source-engine-android-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-engine-iosarm64/0.1.0/source-engine-iosarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-engine-iosarm64/0.1.0/source-engine-iosarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-engine-iosarm64/0.1.0/source-engine-iosarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-engine-iossimulatorarm64/0.1.0/source-engine-iossimulatorarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-engine-iossimulatorarm64/0.1.0/source-engine-iossimulatorarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../source-engine-iossimulatorarm64/0.1.0/source-engine-iossimulatorarm64-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../source-engine-jvm/0.1.0/source-engine-jvm-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../source-engine-jvm/0.1.0/source-engine-jvm-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../source-engine-jvm/0.1.0/source-engine-jvm-0.1.0.module",
        "group": "me.manga.kira.source",
        "module": "source-engine-jvm",
        "version": "0.1.0"
      }
    }
  ]
}
