package me.manga.kira.sources_repositry.ar.dilar.models.info

import kotlinx.serialization.Serializable

@Serializable
data class MangaData(
    val arabic_title: String? = "",
    val banned: Boolean? = false,
    val banner: String? = "",
    val categories: List<Category?>? = listOf(),
    val chaps: Int? = 0,
    val commentable: Boolean? = false,
    val cover: String? = "",
    val cover_pos: Int? = 0,
    val creator_id: Int? = 0,
    val creator_nick: String? = "",
    val editor_id: Int? = 0,
    val editor_nick: String? = "",
    val english: String? = "",
    val genre_id: Int? = 0,
    val id: Int? = 0,
    val is_novel: Boolean? = false,
    val is_oneshot: Boolean? = false,
    val japanese: String? = "",
    val latest_chapterization_id: Int? = 0,
    val mal: String? = "",
    val mangaupdates: String? = "",
    val memberRating: Int? = 0,
    val mobile_exclusive: Boolean? = false,
    val over17: Boolean? = false,
    val rates_count: Int? = 0,
    val rating: String? = "",
    val reading_direction: String? = "",
    val rectangle_cover_pos: Int? = 0,
    val reviewed: Boolean? = false,
    val show_comments: Boolean? = false,
    val story_status: Int? = 0,
    val summary: String? = "",
    val synonyms: String? = "",
    val time_stamp: Int? = 0,
    val title: String? = "",
    val translation_status: Int? = 0,
    val uniq_visitors_count: Int? = 0,
    val vols: Int? = 0,
)