{
  "formatVersion": "1.1",
  "component": {
    "url": "../../source-engine/0.1.0/source-engine-0.1.0.module",
    "group": "me.manga.kira.source",
    "module": "source-engine",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "me.manga.kira.source",
          "module": "source-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "source-engine.aar",
          "url": "source-engine-android-0.1.0.aar",
          "size": 104261,
          "sha512": "8bfe67a19bbed4cb92e6ccaa5f49d9361a1e0d5aff7c66da45ee48af4550390755ecc9ea3f698113fabe366531a90bed33896dca09a6591dae0ce281c9ef316d",
          "sha256": "94316feb00f9c4acb3c8268faa957f8609e04a85f9beecb59a4b1d99fb5fa651",
          "sha1": "41197e77cfc55a3c5da840b19047005afcab9d0f",
          "md5": "b3d769369958e872c2ae90f70b401361"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "me.manga.kira.source",
          "module": "source-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "source-engine.aar",
          "url": "source-engine-android-0.1.0.aar",
          "size": 104261,
          "sha512": "8bfe67a19bbed4cb92e6ccaa5f49d9361a1e0d5aff7c66da45ee48af4550390755ecc9ea3f698113fabe366531a90bed33896dca09a6591dae0ce281c9ef316d",
          "sha256": "94316feb00f9c4acb3c8268faa957f8609e04a85f9beecb59a4b1d99fb5fa651",
          "sha1": "41197e77cfc55a3c5da840b19047005afcab9d0f",
          "md5": "b3d769369958e872c2ae90f70b401361"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "source-engine-android-0.1.0-sources.jar",
          "url": "source-engine-android-0.1.0-sources.jar",
          "size": 33681,
          "sha512": "fe5572679cf8205d50949956ebb39158693713be9aec46c4fb58d411b0b480f2496482aa6f282f8b8dc520b243a8cb8586ea1390dd1ac6a70ccd653f26265ff8",
          "sha256": "84b4b25e9dd952a99c32618bd217571177feabe80801a6a5466e2afbe71e448d",
          "sha1": "0b5f47f1b89f3eb7fb1cfd16fd99ae90d1d89554",
          "md5": "5288d57e3c7e505ab5db335803a46fd1"
        }
      ]
    }
  ]
}
