package me.manga.kira.data.backup.model

import kotlinx.serialization.Serializable

/**
 * Wire format of a Kira backup archive's `backup.json` entry (formatVersion 1).
 *
 * The archive is a STORE-method ZIP whose first entry is this document; optional
 * `downloads/<n>.cbz` entries carry packed downloaded chapters. The same document shape is
 * produced for a full-library export and a scoped (single/multi manga) export — import neither
 * knows nor cares which scope produced a file. Deliberately transport-agnostic: the planned
 * local-network sharing feature reuses this payload unchanged.
 *
 * Forward-compat posture: every non-identity field is defaulted and the decoder runs with
 * `ignoreUnknownKeys = true`, so a formatVersion-1 reader tolerates additive evolution; readers
 * reject only `formatVersion` values above their own.
 */
@Serializable
internal data class BackupFile(
    val formatVersion: Int = 1,
    /** Informational provenance — import never gates on these three. */
    val appVersion: String = "",
    val dbVersion: Int = 0,
    val platform: String = "",
    val createdAtEpochMs: Long = 0,
    val includesDownloads: Boolean = false,
    val mangas: List<BackupManga> = emptyList(),
    val history: List<BackupHistoryItem> = emptyList(),
)

/**
 * One saved manga. Identity for merge-import is `url` first (UNIQUE in the DB), then
 * `(api, title)`. Mirrors `SavedMangaEntity` minus the device-local autogenerated `id`.
 */
@Serializable
internal data class BackupManga(
    val api: String,
    val language: String = "",
    val url: String,
    val imageUrl: String = "",
    val title: String,
    val description: String = "",
    val status: String = "",
    val rating: String? = null,
    val genres: List<String> = emptyList(),
    val savedTimestamp: Long = 0,
    val lastOpenTimestamp: Long = 0,
    val isLiked: Boolean = false,
    val isWatchingNow: Boolean = false,
    val chapters: List<BackupChapter> = emptyList(),
)

/**
 * One chapter. Excludes the device-local columns on purpose: `isDownloaded`/`localImagePaths`
 * are recomputed on the importing device (a packed CBZ travels via [downloadEntry]),
 * `isNew`/`fetchedAt` are transient badge state, and the entity's `lastReadPage` column is dead —
 * the live per-chapter resume position lives in `ReadProgressRepository` and travels here as
 * [resumePage].
 */
@Serializable
internal data class BackupChapter(
    val name: String = "",
    val number: String = "",
    val url: String,
    val dateEpochDay: Long? = null,
    val isRead: Boolean = false,
    val isBookmarked: Boolean = false,
    val lastReadDate: Long = 0,
    val resumePage: Int? = null,
    /** Archive entry path of this chapter's packed CBZ (`downloads/<n>.cbz`), or null. */
    val downloadEntry: String? = null,
)

/** One history row. Keyed by [mangaUrl] on import (one row per manga, newer read wins). */
@Serializable
internal data class BackupHistoryItem(
    val api: String = "",
    val language: String = "",
    val mangaUrl: String,
    val mangaTitle: String = "",
    val mangaImageUrl: String = "",
    val chapterUrl: String = "",
    val chapterTitle: String = "",
    val lastReadDateEpochMs: Long = 0,
    val lastReadPage: Int = 0,
    val totalPages: Int = 0,
)
