package me.manga.kira.platform.cbz

import okio.ByteString.Companion.decodeBase64

// Authored solid-black, 1-bit grayscale PNGs; dimensions change IHDR, not decode-scale tricks.
// Generated from zero-filtered scanlines with zlib level9; no provider/user image data.

/** 8x9 pixels; 68 encoded bytes. */
internal val IOS_CBZ_EXACT_ROWS_PNG: ByteArray = decodeCbzBudgetPng(
    """
    iVBORw0KGgoAAAANSUhEUgAAAAgAAAAJAQAAAAAnKFCDAAAAC0lEQVR42mNgQAcAABIAAeRVjecAAAAASUVORK5CYII=
    """,
)

/** 8x10 pixels; 68 encoded bytes. */
internal val IOS_CBZ_EXTRA_ROW_PNG: ByteArray = decodeCbzBudgetPng(
    """
    iVBORw0KGgoAAAANSUhEUgAAAAgAAAAKAQAAAAChvCItAAAAC0lEQVR42mNgwAQAABQAAe5aaQkAAAAASUVORK5CYII=
    """,
)

/** 7x1 pixels; 67 encoded bytes. */
internal val IOS_CBZ_EXACT_PIXEL_PNG: ByteArray = decodeCbzBudgetPng(
    """
    iVBORw0KGgoAAAANSUhEUgAAAAcAAAABAQAAAAA6cIljAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
    """,
)

/** 8x1 pixels; 67 encoded bytes. */
internal val IOS_CBZ_EXTRA_PIXEL_PNG: ByteArray = decodeCbzBudgetPng(
    """
    iVBORw0KGgoAAAANSUhEUgAAAAgAAAABAQAAAADLe9LuAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
    """,
)

/** 512x16384 pixels; 1112 encoded bytes. */
internal val IOS_CBZ_LARGE_PNG: ByteArray = decodeCbzBudgetPng(
    """
    iVBORw0KGgoAAAANSUhEUgAAAgAAAEAAAQAAAAAPl40HAAAEH0lEQVR42u3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHcDQPAAAdSTSPsAAAAASUVORK5CYII=
    """,
)

/** 16384x1 pixels; 80 encoded bytes. */
internal val IOS_CBZ_TOO_WIDE_PNG: ByteArray = decodeCbzBudgetPng(
    """
    iVBORw0KGgoAAAANSUhEUgAAQAAAAAABAQAAAAAO5Iv1AAAAF0lEQVR42mNgGAWjYBSMglEwCkbBiAMACAEAAfRT8E0AAAAASUVO
    RK5CYII=
    """,
)

private fun decodeCbzBudgetPng(encoded: String): ByteArray =
    checkNotNull(encoded.trimIndent().replace("\n", "").decodeBase64()).toByteArray()
