{
  "formatVersion": "1.1",
  "component": {
    "url": "../../source-contract/0.1.0/source-contract-0.1.0.module",
    "group": "me.manga.kira.source",
    "module": "source-contract",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "source-contract-jvm-0.1.0.jar",
          "url": "source-contract-jvm-0.1.0.jar",
          "size": 139555,
          "sha512": "d96bd8854867e04f834b04cdbd0d0c5770942232222f93741e676d1f0ee3a16aa24aad8eff71c86ca186013c4c229e567f76ceca3fb4a18c787f57094d7edc64",
          "sha256": "9eeb54df5d09f14ebe612b1255721fa536c2517502b05cbd815e8b98370e0b7d",
          "sha1": "ee4ce0d6a9390a82d8b97a515fa4bb081e070566",
          "md5": "3bb69383a6a7c7142b4179f9f1f84ac8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "source-contract-jvm-0.1.0.jar",
          "url": "source-contract-jvm-0.1.0.jar",
          "size": 139555,
          "sha512": "d96bd8854867e04f834b04cdbd0d0c5770942232222f93741e676d1f0ee3a16aa24aad8eff71c86ca186013c4c229e567f76ceca3fb4a18c787f57094d7edc64",
          "sha256": "9eeb54df5d09f14ebe612b1255721fa536c2517502b05cbd815e8b98370e0b7d",
          "sha1": "ee4ce0d6a9390a82d8b97a515fa4bb081e070566",
          "md5": "3bb69383a6a7c7142b4179f9f1f84ac8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "source-contract-jvm-0.1.0-sources.jar",
          "url": "source-contract-jvm-0.1.0-sources.jar",
          "size": 12555,
          "sha512": "63a7a8b797a9963f6a004079810e887030f88cd859cc3b0592f5c900a1598b3ccdaed851baf786735decd5adb364d0d9e994d26697e7f754e9e9dc102b831632",
          "sha256": "ff2332dbd8addbbc69b2c8c3e9c7e6d5e7d1f94e676d532be593a92cd9fafa5b",
          "sha1": "c3a5a836b66335c76c74836d97d18789daabcf7f",
          "md5": "c9902bbd27b278b48cd07e7bd741f7dd"
        }
      ]
    }
  ]
}
